### ISSUE TITLE
Creating 5 topologies

### ISSUE THREAD

**Issue by BhavishyaV** [BhavishyaV/CN-SIM18#1]
We need to create 5 topologies to implement the algorithms.
I have added -
1. A basic 2 node point-to-point topology
2. A dumbell topology

We need to add atleast 3 more

**Comment by mohittahiliani** [comment]
Hi,

You can also consider taking the topology used in:

examples/tutorial/second.cc
examples/tutorial/third.cc
examples/tcp/star.cc

Hope it helps.

**Comment by rachitanaik590** [comment]
Thank you Sir. We will do the needful
