### ISSUE TITLE
wscript for previous versions of ns-3

### ISSUE THREAD

**Issue by mohittahiliani** [BhavishyaV/CN-SIM18#6]
Please provide wscript to link cryptopp with the following versions of ns-3:

ns-3.29
ns-3.28
ns-3.27
ns-3.26
ns-3.25
ns-3.24
ns-3.23
ns-3.22
ns-3.21
ns-3.20

**Comment by mohittahiliani** [comment]
Yes, if you think it would be too much trouble, do it for at least 3 to 4
latest versions.

**Comment by piyushnh** [comment]
Since the latest few versions would be similar, should we check for older versions with release gaps like 3.20, 3.24 and 3.28?
